### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by cjessett** [ll10524/Jammming#4]
(Meets Expectations) Overall, very nice job.

Remember, when writing multiline React components put each prop on a newline. Also, prefer using `const` over `let` when you are not going to reassign the variable.

Otherwise, very nice job on the Spotify module, your code is clean and easy to follow. As a further challenge, add the ability to search for albums and artists as well.

**Comment by limintu** [comment]
Before I move on to the next stage. I have some questions, hoping you can help me.

1. I have completed the ReactJS: Part II. There is a concept called [Stateful and Stateless Component](https://www.codecademy.com/courses/react-102/lessons/stateless-inherit-stateful-intro/exercises/stateless-inherit-stateful). Is it recommended to break [App.js](https://github.com/ll10524/Jammming/blob/master/src/App.js) into two parts? Or, at what scale should I use this concept?

2. Is the entry point for the react app is index.js? This is default or we can specify one? I see no "main" key in the package.json file.
